version: "3.7"

services:

  db-user:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/user/init.sql:/docker-entrypoint-initdb.d/init.sql

  db-chat:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./db/chat/init.sql:/docker-entrypoint-initdb.d/init.sql
