spring:
  datasource:
    url: jdbc:postgresql://db-user:5432/postgres
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 20000 # milliseconds
      maximum-pool-size: 5
