server:
  compression:
    enabled: true

springdoc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    disable-swagger-default-url: true
    path: "/"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 20000 # milliseconds
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
